In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

In [23]:
df = pd.read_csv('loan_approval.csv')
df.head(10)

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
5,Darren Roberts,Port Jesseville,62098,689,19217,29,65.0,True
6,Holly Wood,Lake Joseph,59256,373,40920,40,35.0,False
7,Nicholas Martin,Nelsonside,48289,524,45866,20,25.0,False
8,Patty Perez,Port Leslieview,126530,367,14826,36,55.0,False
9,Emily Rios,Wilkersonmouth,43434,446,18359,8,20.0,False

In [24]:
df.shape

(2000, 8)

In [25]:
print("Unique Values per column:")
df.nunique()

Unique Values per column:

name              2000
city              1882
income            1988
credit_score       537
loan_amount       1968
years_employed      41
points              19
loan_approved        2
dtype: int64

In [26]:
print("Missing Value Per column")
df.isnull().sum()

Missing Value Per column

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

Comment: There is no missing value in this dataset

In [27]:
print("Column Data Type")
display(df.dtypes)

Column Data Type

name               object
city               object
income              int64
credit_score        int64
loan_amount         int64
years_employed      int64
points            float64
loan_approved        bool
dtype: object

In [28]:
le = LabelEncoder()
df['loan_approved'] = le.fit_transform(df['loan_approved'])
df.head(10)

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,0
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,0
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,0
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,0
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,0
5,Darren Roberts,Port Jesseville,62098,689,19217,29,65.0,1
6,Holly Wood,Lake Joseph,59256,373,40920,40,35.0,0
7,Nicholas Martin,Nelsonside,48289,524,45866,20,25.0,0
8,Patty Perez,Port Leslieview,126530,367,14826,36,55.0,0
9,Emily Rios,Wilkersonmouth,43434,446,18359,8,20.0,0

In [29]:
df = df.drop(columns=['name'])
df.head(10)

,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,East Jill,113810,389,39698,27,50.0,0
1,New Jamesside,44592,729,15446,28,55.0,0
2,Lake Roberto,33278,584,11189,13,45.0,0
3,West Melanieview,127196,344,48823,29,50.0,0
4,Mariastad,66048,496,47174,4,25.0,0
5,Port Jesseville,62098,689,19217,29,65.0,1
6,Lake Joseph,59256,373,40920,40,35.0,0
7,Nelsonside,48289,524,45866,20,25.0,0
8,Port Leslieview,126530,367,14826,36,55.0,0
9,Wilkersonmouth,43434,446,18359,8,20.0,0

Comment: Name column is dropped beacause it is identifier feature

In [30]:
df_encoded = pd.get_dummies(
    df,
    columns=['city'],
    dtype=int
)

df_encoded.head(10)

,income,credit_score,loan_amount,years_employed,points,loan_approved,city_Aaronstad,city_Adamburgh,city_Adamland,city_Adammouth,...,city_Wilsonton,city_Wilsonview,city_Wongburgh,city_Woodsburgh,city_Wrightchester,city_Yatesbury,city_Youngbury,city_Yumouth,city_Zacharyton,city_Zamoramouth
0,113810,389,39698,27,50.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,44592,729,15446,28,55.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,33278,584,11189,13,45.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,127196,344,48823,29,50.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,66048,496,47174,4,25.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,62098,689,19217,29,65.0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,59256,373,40920,40,35.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,48289,524,45866,20,25.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,126530,367,14826,36,55.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,43434,446,18359,8,20.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
target_col = "loan_approved" 

X =  df_encoded.drop(columns=[target_col])
Y = df_encoded[target_col]

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=.25,random_state=42)

In [33]:
# Standard Scaling

scaler_std = StandardScaler()

X_train_std = scaler_std.fit_transform(X_train)
X_test_std = scaler_std.transform(X_test)

X_test_std_df = pd.DataFrame(X_test_std,columns=X_test.columns,index=X_test.index)
X_train_std_df = pd.DataFrame(X_train_std,columns=X_train.columns,index=X_train.index)

In [34]:
display(X_train_std_df.head(10))

,income,credit_score,loan_amount,years_employed,points,city_Aaronstad,city_Adamburgh,city_Adamland,city_Adammouth,city_Adamsfort,...,city_Wilsonton,city_Wilsonview,city_Wongburgh,city_Woodsburgh,city_Wrightchester,city_Yatesbury,city_Youngbury,city_Yumouth,city_Zacharyton,city_Zamoramouth
1738,0.828809,-0.653888,1.416707,-0.306828,-0.350568,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
548,1.696654,0.622185,0.956795,-0.475507,0.977342,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
936,-0.016257,1.596192,0.181170,-0.222488,1.508506,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1389,0.226770,-0.542925,1.261327,1.295625,-0.881732,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1607,-1.204337,1.590028,-0.938611,-1.150224,0.446178,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1939,-1.469822,-1.535426,1.012267,1.295625,-1.678478,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1481,0.322072,-0.247024,-1.566357,0.283550,0.180596,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
182,0.034652,-0.425797,-1.098732,-0.475507,-0.350568,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1940,1.678880,0.683831,-0.003644,-0.306828,1.242924,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1160,-1.366723,-0.789509,1.656499,-0.728526,-1.678478,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0

In [35]:
display(X_test_std_df.head(10))

,income,credit_score,loan_amount,years_employed,points,city_Aaronstad,city_Adamburgh,city_Adamland,city_Adammouth,city_Adamsfort,...,city_Wilsonton,city_Wilsonview,city_Wongburgh,city_Woodsburgh,city_Wrightchester,city_Yatesbury,city_Youngbury,city_Yumouth,city_Zacharyton,city_Zamoramouth
1860,1.167517,-0.783344,-0.646249,-0.897205,-0.084986,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
353,-1.050387,1.442077,-1.090524,0.030531,1.508506,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1333,0.447193,0.763971,0.462707,1.211286,0.977342,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
905,-0.468362,0.455741,-1.344537,-0.053809,0.446178,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1289,-1.477764,1.405090,-0.936913,0.789587,0.711760,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1273,1.267008,-0.647723,-1.086491,-0.222488,0.180596,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
938,-0.463154,1.096860,1.177623,-1.740601,-0.084986,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1731,-1.310897,1.670168,1.320126,1.295625,0.446178,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
65,-0.306673,-0.160719,-1.270173,-0.138148,-0.084986,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0
1323,0.821071,0.178334,-1.633575,1.126946,0.977342,-0.025828,-0.025828,0.0,-0.025828,-0.025828,...,0.0,-0.025828,0.0,0.0,-0.025828,-0.025828,-0.025828,0.0,-0.025828,0.0

In [36]:
# MinMax Scaling

scaler_mm = MinMaxScaler()

X_train_mm = scaler_mm.fit_transform(X_train)
X_test_mm = scaler_mm.transform(X_test)


X_train_mm_df = pd.DataFrame(X_train_mm,columns=X_train.columns,index=X_train.index)
X_test_mm_df = pd.DataFrame(X_test_mm,columns=X_test.columns,index=X_test.index)

In [37]:
display(X_test_mm_df.head(10))

,income,credit_score,loan_amount,years_employed,points,city_Aaronstad,city_Adamburgh,city_Adamland,city_Adammouth,city_Adamsfort,...,city_Wilsonton,city_Wilsonview,city_Wongburgh,city_Woodsburgh,city_Wrightchester,city_Yatesbury,city_Youngbury,city_Yumouth,city_Zacharyton,city_Zamoramouth
1860,0.835900,0.267273,0.315944,0.250,0.500000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
353,0.199983,0.923636,0.187741,0.525,0.833333,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1333,0.629369,0.723636,0.635952,0.875,0.722222,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
905,0.366861,0.632727,0.114441,0.500,0.611111,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1289,0.077446,0.912727,0.232068,0.750,0.666667,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1273,0.864426,0.307273,0.188905,0.450,0.555556,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
938,0.368354,0.821818,0.842252,0.000,0.500000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1731,0.125290,0.990909,0.883374,0.900,0.611111,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,0.413220,0.450909,0.135901,0.475,0.500000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1323,0.736567,0.550909,0.031035,0.850,0.722222,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
display(X_train_mm_df.head(10))

,income,credit_score,loan_amount,years_employed,points,city_Aaronstad,city_Adamburgh,city_Adamland,city_Adammouth,city_Adamsfort,...,city_Wilsonton,city_Wilsonview,city_Wongburgh,city_Woodsburgh,city_Wrightchester,city_Yatesbury,city_Youngbury,city_Yumouth,city_Zacharyton,city_Zamoramouth
1738,0.738786,0.305455,0.911244,0.425,0.444444,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
548,0.987614,0.681818,0.778529,0.375,0.722222,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
936,0.496488,0.969091,0.554709,0.450,0.833333,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1389,0.566169,0.338182,0.866407,0.900,0.333333,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1607,0.155843,0.967273,0.231578,0.175,0.611111,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1939,0.079723,0.045455,0.794536,0.900,0.166667,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1481,0.593494,0.425455,0.050432,0.600,0.555556,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
182,0.511085,0.372727,0.185373,0.375,0.444444,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1940,0.982517,0.700000,0.501378,0.425,0.777778,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1160,0.109284,0.265455,0.980440,0.300,0.166667,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0